Remove usage of DatatypeConverter which is not longer automatically available on JDK9 (java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter)